sudo: required
services:
  - docker

before_install:
  - docker build -t joaolbaptista2/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true joaolbaptista2/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-2131254142144"
  bucket_path: "docker"
  on:
    branch: master
  #encrypted keys to let travis connect to AWS in this case
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"